### PR TITLE
Support for buttons with parameters

### PR DESCRIPTION
**Pull request by SolidAlloy**
Hello,

Thank you for the useful plugin!

I added support for methods with parameters. They are rendered like this:
Screenshot 2020-12-07 185214

I had to make some breaking changes in ObjectEditor and ButtonsAttribute to make it work:
- Users need to inherit from ObjectEditor to make a custom editor show the buttons
- ButtonAttribute options are now specified as properties rather than in the attribute constructor

On the positive side, all the time-consuming MethodInfo collecting has moved to OnEnable() and is not called every frame. If a user implements a custom editor and derives it from ObjectEditor, they will be able to draw specific buttons in the places they want rather than drawing all the buttons at once.

Since these are breaking changes, I recommend raising up the package version to 2.0.0.

Please review the code and let me know if something should be changed in terms of code style or how the buttons show up.

### CODE REVIEW

**Comment by SolidAlloy** [comment]
Apparently, when ApplyModifiedProperties() is called for a parameter in Play Mode, a warning like this gets output to console:
"No script asset for System_String_arg. Check that the definition is in a file of the same name."

There is no way to disable that warning, and creating assets at runtime is not an option.
I changed the script so that ApplyModifiedProperties is only called on button press, so there are fewer warnings being output to console, but the problem is still there.

I still think the feature is worth being merged because it has far more advantages than downsides. It is appreciated if someone can help with this though, because I tried everything I could think of 😞

**Comment by madsbangh** [comment]
Thank you! This is cool. I will have a look at it when I get some free time.

W.r.t. the warning you mention, I want to have a look at that and see if it can be avoided somehow, but regardless: Thank you so much :D

**Comment by SolidAlloy** [comment]
Sure, it would be cool if we could get rid of the warning. Here's more info so that you know where to look at:
- The button arguments are ScriptableObjects that are emitted at runtime. Then, a SerializedObject created from each ScriptableObject, and the argument is shown with help of it.
- To be fair, I didn't try creating script assets from those emitted ScriptableObjects at runtime but I highly doubt it can be done easily.
- The warnings are output by C++ backend and can't be disabled by unityLogger.filterLogType or unityLogger.enabled. You can check out [this thread](https://forum.unity.com/threads/how-can-i-delete-a-message-from-unitys-debug-logger.513973/) where people complain about it too.

**Comment by SolidAlloy** [comment]
I finally found a way to get rid of the warning. There is a method `UnityEditor.LogEntry.RemoveLogEntriesByMode()` that can be called through reflection to remove specific logs. The "No script asset for ..." warning has a unique mode that can be used to remove this log entry without affecting all the other logs in the console. The method exists since Unity 2017, so it shouldn't cause any issues for plugin users

**Comment by SolidAlloy** [comment]
Hello, @madsbangh. Any chance we can get this merged? The warning is fixed, and I made a number of additional performance improvements, so only the code style is of concern. I appreciate it if you could review and merge the PR. I would like to use the plugin as a dependency in another plugin being developed by me, and I'd prefer using the original GitHub repo rather than my fork.

By the way, there's an amazing project called [OpenUPM](https://github.com/openupm/openupm) that allows for npm-like management of Unity plugins with auto-resolved dependencies and other features. I would love to see EasyButtons on OpenUPM too, and I can help you with adjusting it to be deployed there, but let's merge this PR first.

**Comment by madsbangh** [comment]
@SolidAlloy Thank you. I finally got around to it! I did not find any issues when testing <3
This is really cool and useful. Again, I appreciate it. Awesome work!

**Comment by madsbangh** [comment]
wrt OpenUPM, I think it would be sweet to get this on there if possible :)

**Comment by SolidAlloy** [comment]
Thanks :)

**Pull request merged**
